export interface CrisisResource {
  name: string;
  detail: string;
  href?: string;
  phone?: string;
}

/** Static, reviewable resources — not generated by the model. */
export const CRISIS_RESOURCES: CrisisResource[] = [
  {
    name: "988 Suicide & Crisis Lifeline (US)",
    detail: "Call or text 988 — 24/7, free, confidential.",
    phone: "988",
    href: "https://988lifeline.org/",
  },
  {
    name: "Crisis Text Line",
    detail: "Text HOME to 741741 (US/CA) — 24/7 crisis support by text.",
    href: "https://www.crisistextline.org/",
  },
  {
    name: "Find a therapist",
    detail: "Psychology Today directory (US) — filter by insurance, modality, and location.",
    href: "https://www.psychologytoday.com/us/therapists",
  },
];

export const CRISIS_SUPPORT_COPY = {
  title: "You are not alone in this moment",
  lead:
    "I can see you are carrying something really heavy right now. What you have shared takes courage. This is beyond what an app can safely address — here are people who specialize in exactly this.",
  footer:
    "This experience is not a diagnosis and it is not judgment. If you are in immediate danger, contact local emergency services.",
} as const;
